#!/usr/bin/python
# vrati zakladne info o shapefajlu
# --layer=0 --feature=0 --features=10 --layers=2
import ogr, argparse

def field_to_str(feature, field_idx):
	field_def = feature.GetFieldDefnRef(field_idx)
	field_key = field_def.GetName()
	field_type = field_def.GetType()
	field_value = feature.GetField(field_idx)
	return '{}({}):{}'.format(field_key, translate_field_type(field_type), field_value)

def translate_field_type(ftype):
	'''http://www.gdal.org/ogr__core_8h.html#a787194bea637faf12d61643124a7c9fc'''
	if ftype == ogr.OFTInteger:
		return 'int32'
	elif ftype == ogr.OFTString:
		return 'string'
	elif ftype == ogr.OFTIntegerList:
		return 'int32_list'
	elif ftype == ogr.OFTReal:
		return 'real'
	elif ftype == ogr.OFTInteger64:
		return 'int64'
	elif ftype == org.OFTBinary:
		return 'binary'
	elif ftype == ogr.OFTDate:
		return 'date'
	elif ftype == ogr.OFTTime:
		return 'time'
	else:
		return str(ftype)
	
def translate_geometry_type(gtype):
	'''http://www.gdal.org/ogr__core_8h.html#a800236a0d460ef66e687b7b65610f12a'''
	if gtype == ogr.wkbUnknown:
		return 'unknown'
	elif gtype == ogr.wkbPoint:
		return 'point'
	elif gtype == ogr.wkbLineString:
		return 'line_string'
	elif gtype == ogr.wkbPolygon:
		return 'polygon'
	else:
		return str(gtype)

def main(args):
	print(args)
	
	
	source = ogr.Open(args.input_file)
	print('layers: {}'.format(source.GetLayerCount()))

	if args.layers is None:
		max_layer = source.GetLayerCount()
	else:
		max_layer = min(args.layers, source.GetLayerCount())

	for i in range(0, max_layer):
		layer = source.GetLayer(i)
		print('layer_{}: features={}'.format(i, layer.GetFeatureCount()))
		
		if args.features is None:
			max_feature = layer.GetFeatureCount()
		else:
			max_feature = args.features
		
		for j in range(0, max_feature):
			feature = layer.GetFeature(j)
			geom = feature.GetGeometryRef()
			geom_type = geom.GetGeometryType()
			print('  feature_{}: geometry={}, fields={}'.format(j,
				translate_geometry_type(geom_type), feature.GetFieldCount()))
			print('    geometry: {}'.format(geom))
			
			for k in range(feature.GetFieldCount()):
				print('    {}'.format(field_to_str(feature, k)))


	print('done!')

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument('--layers', type=int, help='layers')
	parser.add_argument('--features', type=int, help='features')
	parser.add_argument('input_file', type=str, nargs='?', help='input_file')
	main(parser.parse_args())





