# Pre skompilovanie release verzie zadaj prikaz '$ scons mode=release'.
use_clang = False

env = Environment()

build_mode = ARGUMENTS.get('mode', 'debug')

if build_mode == 'debug' and use_clang:
	env['CC'] = 'clang'
	env['CXX'] = 'clang++'

common_ccflags = '-std=c++11 '
release_ccflags = common_ccflags + '-O3 -DRELEASE '
debug_ccflags = common_ccflags + '-g -O0 -DDEBUG '


if build_mode == 'debug':
	ccflags = debug_ccflags
else:
	ccflags = release_ccflags

env.ParseConfig('xml2-config --cflags --libs')

print '+++Compiling in ' + build_mode + ' mode+++'

env.Program(
	['graph_generator.cpp', 'reader_impl.cpp'],
	CCFLAGS=ccflags,
	LIBPATH='.'
)

