env = Environment(
	CCFLAGS=['-std=c++14', '-O0', '-g', '-Wall'],
	CPPPATH=['agg-2.5/include'],
	LIBS=['bz2', 'z', 'pthread']
)

# build library with x11 support

env.ParseConfig('pkg-config --cflags --libs x11 expat')

agg_lib = env.StaticLibrary('agg', [
	Glob('agg-2.5/src/*.cpp'),
	Glob('agg-2.5/src/ctrl/*.cpp'),
	Glob('agg-2.5/src/platform/X11/*.cpp')
])

objs = env.Object(['road_reader.cpp'])

env.Program(['road_render.cpp', objs, agg_lib])
env.Program(['conv_stroke.cpp', objs, agg_lib])

# unit tests
env.Program(['test.cpp', Glob('test_*.cpp'), objs])
