# Pre skompilovanie release verzie zadaj prikaz '$ scons mode=release'.

env = Environment(
	CCFLAGS = ['-std=c++11', '-Wall'],
	CPPPATH = ['libs'],
	CPPDEFINES=['GLM_FORCE_RADIANS'],
	LIBS = ['Geographic']
)

env.ParseConfig('xml2-config --cflags --libs')

build_mode = ARGUMENTS.get('mode', 'debug')
if build_mode == 'release':
	env['CCFLAGS'].append('-O3')
else:
	env['CCFLAGS'].append(['-g', '-O0'])

print '+++Compiling in ' + build_mode + ' mode+++'

osmut_objs = env.Object(Glob('libs/osmut/*.cpp'))
graph_objs = env.Object(Glob('libs/graph/*.cpp'))
objs = [graph_objs, osmut_objs]

env.Program(['roadgraph.cpp', objs])
