# Pre skompilovanie release verzie zadaj prikaz '$ scons mode=release'.

env = Environment(
	#CXX=['clang++'],
	CPPPATH=['osmut', '.'],
	CXXFLAGS=['-std=c++11'],
	CCFLAGS=['-Wall'],
	LIBS=['boost_regex', 'gtest', 'pthread']
)

env.ParseConfig('xml2-config --cflags --libs')

build_mode = ARGUMENTS.get('mode', 'debug')
if build_mode == 'release':
	env.Append(CCFLAGS=['-O3'])
else:
	env.Append(CCFLAGS=['-g', '-O0'])

print '+++Compiling in ' + build_mode + ' mode+++'

# libs
osmut_objs = env.Object(Glob('osmut/*.cpp'))

# tests
env.Program(['test_osmreader.cpp', osmut_objs])

# utilities
env.Program('osmreader', ['osmreader.cpp', osmut_objs])
env.Program('waytypes', ['waytypes.cpp', osmut_objs])
env.Program('extractway', ['extractway.cpp', osmut_objs])
env.Program('listways',	['listways.cpp', osmut_objs])
env.Program('osmfilter', ['osmfilter.cpp', osmut_objs])
